
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 18 17:13:36 CST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 15;
  public static final int Coma = 30;
  public static final int Llave_c = 22;
  public static final int Op_booleano = 18;
  public static final int Llave_a = 21;
  public static final int If = 4;
  public static final int Void = 31;
  public static final int T_dato = 3;
  public static final int Else = 5;
  public static final int Ingresar = 36;
  public static final int Break = 40;
  public static final int Pow = 39;
  public static final int Corchete_c = 24;
  public static final int Corchete_a = 23;
  public static final int Return = 32;
  public static final int While = 7;
  public static final int Division = 13;
  public static final int Math = 29;
  public static final int Cadena = 33;
  public static final int Parentesis_c = 20;
  public static final int Parentesis_a = 19;
  public static final int For = 8;
  public static final int EOF = 0;
  public static final int P_coma = 26;
  public static final int error = 1;
  public static final int Imprimir = 35;
  public static final int Char = 34;
  public static final int Op_atribucion = 16;
  public static final int ERROR = 41;
  public static final int Do = 6;
  public static final int Op_logico = 14;
  public static final int Identificador = 27;
  public static final int Mod = 37;
  public static final int Resta = 11;
  public static final int Raiz = 38;
  public static final int Multiplicacion = 12;
  public static final int Op_incremento = 17;
  public static final int Numero = 28;
  public static final int Suma = 10;
  public static final int Main = 25;
  public static final int Igual = 9;
  public static final int Comillas = 2;
}

